#    â”â”“â”â”³â”“â”â”“â”³â”“â”â”“â”“â”â”³â”â”“
#    â”—â”“ â”ƒ â”£â”«â”£â”«â”—â”“â”£â”«â”ƒâ”ƒâ”ƒ
#    â”—â”› â”» â”›â”—â”›â”—â”—â”›â”›â”—â”»â”£â”›
#    TSUKIYOSHIP ( A Minimalistic Starship Prompt )
# ~/.config/starship.toml

format = """
[\\[](bold bright-blue) $username[ğœ¸¨](bold bright-green)$directory$git_branch$git_status [\\]](bold bright-blue) $character
"""

# Username
[username]
show_always = true
format = "[$user](bold bright-red)"

# Directory
[directory]
home_symbol = 'home'
truncation_length = 2
truncation_symbol = 'â€¦/'
truncate_to_repo = false
read_only = ' ro'
read_only_style = 'bold bright-red'
format = "[$path](bold bright-white)[$read_only]($read_only_style)"

# Git branch
[git_branch]
symbol = "ï˜ "
format = " [\\(](bold bright-white)[$symbol$branch](bold bright-yellow)"

# Git status (characters + bright colors)
[git_status]
format = "$all_status$ahead_behind[\\)](bold bright-white)"
conflicted = "[ îª‡ $count](bright-red)"
ahead      = "[ ó±–— $count](bold bright-blue)"
behind     = "[ ó±–™ $count](bold bright-blue)"
diverged   = "[ ó°¿¤ $count](bold bright-red)"
untracked  = "[ ó°»ƒ $count](bold bright-yellow)"
stashed    = "[ ó°™§ $count](bold bright-cyan)"
modified   = "[ ó°º• $count](bold bright-yellow)"
staged     = "[ ó°—¡ $count](bold bright-green)"
renamed    = "[ ó±–˜ $count](bold bright-magenta)"
deleted    = "[ ó°…š $count](bold bright-red)"

# Character module â€” keep the prompt character fixed as "â€¢â€º"
[character]
success_symbol = "[î®Šâ±](bright-green)"
error_symbol   = "[î®Šâ±](bright-red)"
format = "$symbol "
